# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: luang@umich.edu
author_name: etc_jupyterlab_hints
has_binder: false
has_settings: false
kind: frontend
labextension_name: etc_jupyterlab_hints
project_short_description: A JupyterLab extension that provides hint for University
    of Michigan Jupyter Notebook courses.
python_name: etc_jupyterlab_hints
repository: ''
test: true

